### ISSUE TITLE
Recommended |ota command should not hardcode ~marzod

### ISSUE THREAD

**Issue by ritfed-tabryg** [dcSpark/urbit-visor#92]
`~marzod` has a lot to do, being a heavily loaded star and often the first third-party star people think to run an `|ota` command for. Even comets have a sponsor star, so the command `|ota (sein:title our now our) %kids` will sync from the comet's parent and more evenly distribute the load of distributing OTAs across the network.

It's also worth mentioning that after the [app distribution/Grid update](https://urbit.org/using/os/dist-faq), the `|ota` command no longer exists, and updates are controlled per-app with the `|install` command, so the relevant section about updating in the README needs to be changed.

**Comment by robkorn** [comment]
Thanks for pointing this out, that's indeed a good idea to not hardcode ~marzod.

In this case the OTA command is still relevant since the specific error takes place if the comet is old enough to miss required scries that we need. We will likely remove that part of the faq in the near future once it's no longer relevant.
